[package]
name = "ictest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
highlight_error = "0.1.1"
once_cell = "1.17.0"

[dev-dependencies]
proptest = "1.0.0"
